#!/bin/bash

pdf=$1
RPTMP=/tmp/replace.sed

# This script repairs a pdf file generated by **pdfroff** which has misaligned co-ordinates for its bookmarks and anchor link. The key value to adjust here is the numbers in the string $1+50. Unlike a previous version of the script, this script generates everything necessary from the original PDF file and deletes all working files when done.

grep -a "FitH*" $pdf | awk -F" " '{print $6}' | awk -F"]" '{print $1}' | awk -F. '{print "s/"$0"/"($1+50)"."$2"/g"}' >$RPTMP

# The previous line reads the PDF, which is provided as the first argument after calling this script, and generates a temporary **.sed** file, containing all of the FitH values that need to be adjusted. You may change the location of the **.sed** file by modifying the RPTMP variable above.

sed -f "$RPTMP" "$pdf" >"$(sed 's/\.[pP][dD][fF]$//' <<<"$pdf")_adjust.pdf"

# This line uses the values in the **.sed** file to generate a new PDF with all correct values. It has the same name as the original PDF with "_adjust.pdf" appended to the end.

rm $RPTMP # This line deletes the temporary **.sed** file.
